site_name: NeedCoolerShoes Wiki
site_url: https://wiki.needcoolershoes.com
theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    # - media: "(prefers-color-scheme: light)"
    #   scheme: default
    #   primary: deep orange
    #   accent: deep purple
    #   toggle:
    #     icon: material/lightbulb
    #     name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: deep purple
      # toggle:
      #   icon: material/lightbulb-outline
      #   name: Switch to light mode
  features:
    - header.autohide
    - announce.dismiss
    - navigation.footer
repo_url: https://github.com/needcoolershoes/wiki
repo_name: needcoolershoes
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
  - git-committers:
      enabled: true
      repository: needcoolershoes/wiki
      branch: main
  - privacy
  - social
copyright: <a href="https://creativecommons.org/licenses/by-sa/4.0/">Licensed under CC BY-SA 4.0<a>
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/needcoolershoes/
    - icon: fontawesome/brands/discord
      link: https://discord.gg/FEfbZYvQUa
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/needcoolershoes.com
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@needcoolershoes
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences